---
name: whitespace-linter
author: Nick Osborn
description: Check for superfluous whitespace

inputs:
  files:
    description: files, directories, or globs
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: check-circle
  color: purple
